name: build-windows-portable

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - "ai-manager-backend/**"
      - "scripts/windows/**"
      - "Progress/**"
      - "config.json"

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show env
        run: |
          java -version
          python --version
          powershell $PSVersionTable

      - name: Build Windows portable bundle
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          .\scripts\windows\build_windows_portable.ps1

      - name: Upload artifact (Windows Offline Bundle)
        uses: actions/upload-artifact@v4
        with:
          name: AI_Manager_Windows_Offline
          path: dist/AI_Manager_Windows_Offline/**
          if-no-files-found: error
